### ISSUE TITLE
Contract is not working

### ISSUE THREAD

**Issue by ArseniiPetrovich** [gnosischain/deposit-contract#23]
For some reason even given the fact I followed all the instructions - I face the following issues when trying to run a batch of 1 calls over 1 validator. Could you please check?
I also tried both compiled version from dockerhub and version I've compiled myself.
```
Fetching existing deposits
(node:7) UnhandledPromiseRejectionWarning: Error: This contract object doesn't have address set yet, please set an address first.
    at Object.ContractNoAddressDefinedError (/app/node_modules/web3-eth/node_modules/web3-core-helpers/lib/errors.js:122:16)
    at Contract._generateEventOptions (/app/node_modules/web3-eth/node_modules/web3-eth-contract/lib/index.js:534:22)
    at Contract.getPastEvents (/app/node_modules/web3-eth/node_modules/web3-eth-contract/lib/index.js:635:49)
    at getPastLogs (/app/scripts/deposit.js:133:21)
    at main (/app/scripts/deposit.js:73:26)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:7) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:7) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by ArseniiPetrovich** [comment]
I was missing:
```
# address of the GBC deposit contract
DEPOSIT_CONTRACT_ADDRESS=0x0B98057eA310F4d31F2a452B414647007d1645d9
```

**Comment by akolotov** [comment]
The documentation on https://docs.gnosischain.com/validator-info/validator-deposits/manual-deposit-method has been updated to reflect proper configuration for the deposit script. Thanks!
